### ISSUE TITLE
评审字段配置新增和修改功能接口异常

### ISSUE THREAD

**Issue by chemian** [veezean/CodeReviewServer#8]
![image](https://user-images.githubusercontent.com/62023920/230873572-f185607f-cd3c-42e4-8a79-0d48a7247a71.png)

**Comment by GloomyNAN** [comment]
pom文件23行升级下erupt

```xml
<erupt.version>1.11.5</erupt.version>
```
等下我提个PR ；

[erput-release](https://github.com/erupts/erupt/releases)

<img width="1147" alt="image" src="https://user-images.githubusercontent.com/9264987/233814017-00cf4e82-24a0-4774-83e6-5c532f1c9e8b.png">

**Comment by veezean** [comment]
之前的服务端版本采用了erupt来自动生成界面，效果太差，定制化能力比较弱。
已经采用vue重新写了一版，已经合入主干分支，欢迎试用。
此问题关闭了。
